### ISSUE TITLE
Error during npm start

### ISSUE THREAD

**Issue by dcabib** [victordibia/handtrack.js#2]
$ npm start

> handtrackjs@0.0.13 start /private/tmp/handtrack.js
> cross-env NODE_ENV=development parcel demo/index.html --open

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn parcel ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! handtrackjs@0.0.13 start: `cross-env NODE_ENV=development parcel demo/index.html --open`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the handtrackjs@0.0.13 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/abib/.npm/_logs/2019-03-13T10_17_17_633Z-debug.log

**Comment by victordibia** [comment]
Hi @dcabib   

> `Error: spawn parcel ENOENT`

The error above suggests you dont have parceljs installed.
I have updated the start script launch a simple `python3` webserver from the demo folder using `http.server`.

-V.
