### ISSUE TITLE
handtrack not work in vue3+vite3

### ISSUE THREAD

**Issue by Jackie-Tang** [victordibia/handtrack.js#75]
engine.ts:586 Uncaught (in promise) TypeError: t3 is not a function
    at engine.ts:586
    at engine.ts:424
    at t2.scopedRun (engine.ts:435)
    at t2.tidy (engine.ts:422)
    at f2 (engine.ts:586)
    at engine.ts:599
    at t2.scopedRun (engine.ts:435)
    at t2.runKernelFunc (engine.ts:596)
    at t2.runKernel (engine.ts:493)
    at clone_2 (clone.ts:47)

**Comment by foolhardy21** [comment]
facing a similar issue in react app as well. 
`("react": "^17.0.1", "handtrackjs": "^0.1.5",)`

error:
```
TypeError: t is not a function
    at tf-core.esm.js:17:1
    at tf-core.esm.js:17:1
    at t.scopedRun (tf-core.esm.js:17:1)
    at t.tidy (tf-core.esm.js:17:1)
    at f (tf-core.esm.js:17:1)
    at tf-core.esm.js:17:1
    at t.scopedRun (tf-core.esm.js:17:1)
    at t.runKernelFunc (tf-core.esm.js:17:1)
    at t.runKernel (tf-core.esm.js:17:1)
    at clone_ (clone.ts:47:1)
    at clone__op (operation.ts:51:1)
    at cloneTensor (utils.ts:162:1)
    at Module.executeOp (control_executor.ts:131:1)
    at operation_executor.ts:65:1
    at executeOp (operation_executor.ts:115:1)
    at GraphExecutor.processStack (graph_executor.ts:492:1)
    at GraphExecutor.executeWithControlFlow (graph_executor.ts:439:1)
    at GraphExecutor._executeAsync (graph_executor.ts:357:1)
    at GraphExecutor.executeAsync (graph_executor.ts:321:1)
    at GraphModel.executeAsync (graph_model.ts:362:1)
    at ObjectDetection.load (index.js:171:1)
    at async Module.load (index.js:93:1)
```

**Comment by punkpette** [comment]
I have a similar issue
also vue 3 + vite latest version

```
engine.ts:424 
 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'backend')
    at _Engine.moveData (engine.ts:424:29)
    at DataStorage.get (backend.ts:54:22)
    at _MathBackendWebGL.incRef (backend_webgl.ts:204:34)
    at Object.identity2 [as kernelFunc] (Identity.ts:27:11)
    at kernelFunc (engine.ts:636:22)
    at engine.ts:703:23
    at _Engine.scopedRun (engine.ts:478:19)
    at _Engine.runKernelFunc (engine.ts:699:10)
    at _Engine.runKernel (engine.ts:543:17)
    at clone_ (clone.ts:47:17)
```

any chance this gets fixed soon? i see this issue was opened on 2022...

**Comment by yunshengya** [comment]
tf-core.esm.js:303 Uncaught (in promise) TypeError: t is not a function
    at eval (tf-core.esm.js:303:43059)
    at eval (tf-core.esm.js:303:41148)
    at t.scopedRun (tf-core.esm.js:303:41287)
    at t.tidy (tf-core.esm.js:303:41045)
    at f (tf-core.esm.js:303:43035)
    at eval (tf-core.esm.js:303:43368)
    at t.scopedRun (tf-core.esm.js:303:41287)
    at t.runKernelFunc (tf-core.esm.js:303:43180)
    at t.runKernel (tf-core.esm.js:303:41724)
    at clone_ (clone.js:48:56)
    at clone__op (operation.js:51:28)
    at cloneTensor (utils.js:139:95)
    at Module.executeOp (control_executor.js:114:72)
    at eval (operation_executor.js:76:81)
    at executeOp (operation_executor.js:118:7)
    at GraphExecutor.processStack (graph_executor.js:399:106)
    at GraphExecutor.executeWithControlFlow (graph_executor.js:359:35)
    at GraphExecutor._executeAsync (graph_executor.js:294:38)
    at GraphExecutor.executeAsync (graph_executor.js:266:21)
    at GraphModel.executeAsync (graph_model.js:327:44)
    at ObjectDetection.load (index.js:182:37)
    at async Module.load (index.js:104:3)  报错信息如上 什么原因
